stages:
  - stage: Stage
    jobs:
      - job: Foo
        steps:
          - template: foo.yml
            parameters:
              bool_true_explicit: true
              bool_false_explicit: false
              string_true_explicit: 'true'
              string_false_explicit: 'false'
