stages:
  - stage: Stage
    jobs:
      - job: Foo
        pool:
          vmImage: windows-latest

        steps:
          - bash: which tar
          - bash: ls -l /bin
          - bash: ls -l /usr/bin
          - bash: tar -h
