parameters:
  array1: ''
  array2: ''
  array3: 'default'
  foo: false
  bar: 42
  baz: { foo: "bar" }

stages:
  - stage: Stage1
    jobs:
      - job: ShowParams
        pool:
          vmImage: ubuntu-16.04
        steps:
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: env|sort
            env: ${{ parameters }}

