parameters:
  array1: ''
  array2: ''
  array3: [ 'default', 'value' ]

stages:
  - stage: Stage1
    jobs:
      - job: ShowParams
        pool:
          vmImage: ubuntu-16.04
        steps:
          - bash: |
              echo "array1 = ${{ join(',', parameters.array1) }}"
              echo "array2 = ${{ join(',', parameters.array2) }}"
              echo "array3 = ${{ join(',', parameters.array3) }}"
              echo "array1 has 1 = ${{ containsValue( parameters.array1, 1 ) }}"
              echo "array1 has '1' = ${{ containsValue( parameters.array1, '1' ) }}"
